### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by bradfrost** [maban/styleguides#10]
Hey All,
First of all, thanks for setting this up! I'm just now getting in front of my computer after wrapping up a few obligations, so thanks for doing all the groundwork. The site looks great already!

As for where this should live, I think it would be a great idea to get a dedicated domain for this resource. Hosting on Github can be weird URL-wise, and living on any one person's site could sell it short. So yeah, do you all have any suggestions for domains?

Domains like styleguid.es, webstyleguides.com, etc are taken. Generally-speaking, a reasonably self-explanatory domain would be nice. styleguides.io seems to be available. Any other suggestions?

**Comment by maban** [comment]
I suck at names.

I like styleguides.io – one thing I'm wondering is how broad we want to make it. Style guides is a general term and I don't want to confuse it with print ones, but it'd also give us the freedom to make it more general if we want to.

**Comment by bradfrost** [comment]
I think being broad is a good thing. Being too specific can be limiting over time (Flash on the Beach etc), so I think a bigger umbrella is a good thing. I'll go ahead and snag styleguides.io and we can go from there, if that works for you all!

**Comment by brendanfalkowski** [comment]
I'd stay broad too, but aren't .io domains a bit pricey (for a micro-site)? Thanks for volunteering @bradfrost just don't want you saddled with it (I'm sure we all have domain skeleton closets).

**Comment by maban** [comment]
Sounds good! Brad, if you haven't already, I'd be happy to buy the domain. I can business-expense it.

**Comment by susanjrobertson** [comment]
Sounds like this is done, so closing!
