### ISSUE TITLE
"Recommended" resources

### ISSUE THREAD

**Issue by maban** [maban/styleguides#11]
There are now a lot of resources, so I've been adding `status: recommended` to the YAML front-matter on resources I want to highlight. This should make it easier for people who are looking for just a few good examples to look at. It's a bit biased just me doing it, and there are a few links I haven't had time to look at properly, particularly the talks, so please add the 'recommended' tag if you're familiar with them and think they deserve highlighting.

**Comment by bradfrost** [comment]
I think that's a great idea, and is something I do with This Is Responsive resources as well. There's a lot of stuff out there, but if you had to read _one_ thing on a topic, it's good to float a particularly good resource to the top.

**Comment by susanjrobertson** [comment]
I will ponder and go through content to figure out what I would recommend :)

**Comment by susanjrobertson** [comment]
Alright, I looked at what was there and recommended the one thing that I did already have it, but I don't all the other resources (need a weekend to read, play, etc).
