### ISSUE TITLE
Examples page: Dell image link missing/broken

### ISSUE THREAD

**Issue by benbrignell** [maban/styleguides#121]
![image](https://cloud.githubusercontent.com/assets/362340/7277909/69c02c66-e90a-11e4-8356-97bd16ec8e76.png)

**Comment by michaelthorne** [comment]
![dell](https://cloud.githubusercontent.com/assets/2629322/7278244/6478c5c4-e914-11e4-9741-5358d9379923.png)

Should be good now?
