### ISSUE TITLE
Header reflows and breaks at around 1004px

### ISSUE THREAD

**Issue by benbrignell** [maban/styleguides#123]
![image](https://cloud.githubusercontent.com/assets/362340/7288012/8081913a-e953-11e4-9824-a56dbefabddf.png)

**Comment by maban** [comment]
Pushed some fixes to this in https://github.com/maban/styleguides/commit/e5704b5f401ef6a7be0bd7c4684e57566b21cfde – going to see how it goes.

![screen shot 2017-01-13 at 15 01 05](https://cloud.githubusercontent.com/assets/237149/21934424/43be2f98-d9a1-11e6-8644-c7490f94c0bc.png)
<img width="334" alt="screen shot 2017-01-13 at 15 01 39" src="https://cloud.githubusercontent.com/assets/237149/21934423/43bdcd28-d9a1-11e6-92e9-764fa9ff91b6.png">
![screen shot 2017-01-13 at 15 02 43](https://cloud.githubusercontent.com/assets/237149/21934453/5e65e192-d9a1-11e6-82ff-99c165518faf.png)
![screen shot 2017-01-13 at 15 02 48](https://cloud.githubusercontent.com/assets/237149/21934454/5e81e4c8-d9a1-11e6-8dd5-d6dfc9f82021.png)

**Comment by maban** [comment]
My only concern it that it's a little mystery-meat navigation at small sizes.
