### ISSUE TITLE
Filters break

### ISSUE THREAD

**Issue by bradfrost** [maban/styleguides#124]
![examples](https://cloud.githubusercontent.com/assets/383701/7288562/8540dcfc-e931-11e4-8237-795186da717f.png)

Clicking on the filters a few times will break the filtering functionality. It looks like the `data-toggle="off"` persists and is causing issues.

**Comment by brendanfalkowski** [comment]
I got some time back.

`You built a time machine out of a DeLorean?`

Can hack on the filter bugs. Need to get this Jekyll thing working locally though. Wasn't super great pushing in code to test on the site.

**Comment by bradfrost** [comment]
![tumblr_mlvwtbphfe1r7emqio1_500](https://cloud.githubusercontent.com/assets/383701/7416309/0849f974-ef24-11e4-8918-305adb480541.gif)

**Comment by maban** [comment]
Changed the functionality of the tags a little, so this is fixed now.
