### ISSUE TITLE
Grid layout issues when filtering

### ISSUE THREAD

**Issue by bradfrost** [maban/styleguides#125]
![examples](https://cloud.githubusercontent.com/assets/383701/7288579/d999c49e-e931-11e4-94bc-7631fedc2bf2.png)

When filters are triggered, the layout often breaks onto separate lines. This has to do with the `clear: left` rules applied to the grid, such as `.resource:nth-child(4n+1) { clear: left; }`. 

Perhaps a solution could be to use flexbox and `flex-wrap`? That would fix the issue and would also give us the bonus of being able to set the height of each `.resource` in a row to be the same height.

**Comment by maban** [comment]
Fixed!
