### ISSUE TITLE
Update URL on filter

### ISSUE THREAD

**Issue by bradfrost** [maban/styleguides#126]
It would be great to update the hash in the URL (i.e. `styleguides.io/examples.html#branding`) so that we can link to a particular flavor of style guide. 

Without looking at the logic, I think this would require having each filter be mutually exclusive. As in, you wouldn't be able to search for branding+code, but I don't see that as being a core use case any way. Being able to filter and see all branding _or_ all code style guides would be more of a primary use case.

**Comment by maban** [comment]
Want.

**Comment by maban** [comment]
This was done, thanks to @codegaze's work.
