### ISSUE TITLE
Crashing mobile browsers

### ISSUE THREAD

**Issue by walkerde** [maban/styleguides#127]
safari, Twitter, and chrome. Even Pocket view.

**Comment by benbrignell** [comment]
I can't seem to replicate this, can you provide any more info?

**Comment by bradfrost** [comment]
I can't replicate either, but at the same time we should probably look into
some sort of lazy loading solution to prevent 50+ images from loading.

On Thursday, April 23, 2015, Ben Brignell notifications@github.com wrote:

> I can't seem to replicate this, can you provide any more info?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maban/styleguides/issues/127#issuecomment-95510073.

## 

---

Brad Frost
http://bradfrost.com
http://twitter.com/brad_frost

**Comment by walkerde** [comment]
I go to sleep. I wake up. And now no issues. Can't replicate either. Odd. Wish I was more help. 

First looked at it in Twitter's browser view off Brad's tweet. Crashed. 

Sent to Pocket, tried to view there. Crashed. 

Opened out in Safari. Crashed. 

Copy pasted into Chrome. Crashed. 

iPhone 6+ all apps and OS up to date.

**Comment by benbrignell** [comment]
What twitter client are you using @walkerde? It's probably something to do with the amount of images - but I did quickly test and it seemed ok. I agree with @bradfrost we should have a more smarter way of loading them now there are a lot more. 

Among others, I have tested this with a couple of very basic Android devices and it still loads fine for me, no memory/crashes from images, at least so far.

**Comment by benbrignell** [comment]
Looked at it on a few more things now, still no issues. Images definitely would benefit from lazy loading. Perhaps @walkerde looking at the time of your tweet, maybe you happened to load it just as the build happened and had some caching problems weirdnessification.

**Comment by benbrignell** [comment]
ok, I've thrown this around to a few people - nobody else has had it crash. So I suggest this get closed @bradfrost (I don't think I have perms to close the issue) - I will open an enhancement suggestion for lazy loading, and if @walkerde has it happen again we reopen with steps to replicate.

**Comment by bradfrost** [comment]
Alright we'll close this out for now, but yep it's definitely a good idea to open an enhancement issue to smartly load images.
