### ISSUE TITLE
Branding Guides

### ISSUE THREAD

**Issue by bradfrost** [maban/styleguides#13]
I have a _ton_ of examples of brand style guides. While they're a bit deeper in scope than web style guides, do you think it's a good idea to include these into the mix? Again, the lines can be a bit gray, but I personally think it would be helpful to round these up as well.

**Comment by maban** [comment]
Go for it!

**Comment by maban** [comment]
I might add a separate category for these – maybe rename examples to "front-end style guides" and put these in one called "branding style guides". Or something.

**Comment by allardvanhelbergen** [comment]
We might also just want to link out to some existing sites that already collect branding guidelines, to keep the site focussed. 

The following are some good collections:
- [FindGuidelin.es](http://findguidelin.es/) 
- [Corporate Identity Portal](http://www.ci-portal.de/styleguides/)
- [Design Tagebuch](http://www.designtagebuch.de/wiki/corporate-design-manuals/)
- [Logo Design Love](http://www.logodesignlove.com/brand-identity-style-guides)
- [The Logo Smith](http://imjustcreative.com/category/identity-guidelines) _Some historical gems in this one_

**Comment by bradfrost** [comment]
It's fine for the branding guidelines to exist on the site, and we now have filters in place to sort things accordingly. Thanks for sharing these other guideline roundups as well!

**Comment by allardvanhelbergen** [comment]
Ok, thanks @bradfrost . I'll prepare a PR for some of the nicer/more outstanding ones over the next couple of days, shall I?
