### ISSUE TITLE
Default Sort - Alphabetical

### ISSUE THREAD

**Issue by whitingx** [maban/styleguides#130]
On the examples page, it might be useful if the default order was alphabetical to allow easier browsing/finding of examples based on known name (e.g. if a user is looking for the IBM Design Language example they know it comes under 'I')

Seems like Jekyll does allow for this - http://www.leveluplunch.com/blog/2014/04/03/sort-pages-by-title-filter-array-by-layout-jekyllrb/

**Comment by bradfrost** [comment]
Hey there, thanks for the suggestion. I think it's a good idea to look into this, however I want to make sure we keep the featured (star) items at the top of the list.

**Comment by whitingx** [comment]
Good idea @bradfrost - in this case perhaps there could be better definition of the _starred_ items, broken out into a separate 'featured' type section perhaps?

Could then work along the lines of;

---

## starred items (alpha sort)

## other items (alpha sort)

??

**Comment by bradfrost** [comment]
Yeah it would definitely be two separate loops, but we'd still want them
displayed together. The obvious idea behind the featured items is to
surface particular stellar/seminal examples and resources, so if users
don't have time to view them all they can check out a few good ones.

On Friday, May 1, 2015, whitingx notifications@github.com wrote:

> Good idea @bradfrost https://github.com/bradfrost - in this case
> perhaps there could be better definition of the _starred_ items, broken
> out into a separate 'featured' type section perhaps?
> 
> ## Could then work along the lines of;
> 
> starred items (alpha sort) other items (alpha sort)
> 
> ??
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maban/styleguides/issues/130#issuecomment-98102890.

## 

---

Brad Frost
http://bradfrost.com
http://twitter.com/brad_frost

**Comment by maban** [comment]
I've added this, using 2 separate loops to keep the recommended resources at the top. It'll also help us spot where we have duplicate entries.

**Comment by whitingx** [comment]
That's great, thanks @maban :) Make the resources easier to scan/find :+1:
