### ISSUE TITLE
Lazy loading of images

### ISSUE THREAD

**Issue by benbrignell** [maban/styleguides#132]
#### Lazy loading `Enhancement`

Now there's a lot more images on the examples page it would be a good idea to lazy load (or have a smarter way of loading) a large amount of images.

It would be nice to start collecting the images for all the other resources but it's probably going to get slow.

**Comment by whitingx** [comment]
Wonder if it would also be useful to automate this screenshot process for when new resources are added.

Could use one of the _screenshot>image_ API services available (e.g. http://www.page2images.com/website_thumbnail_api_document) to remove the manual step of adding individual screenshots.

As this could be done off the URL used to link to the style guide resource it would have the benefit of being able to set a refresh time to ensure the screenshot is always up-to-date. Might also be possible to use this to highlight when resource URLs change - if the screenshot API fails the resource link could be checked/updated.

**Comment by benbrignell** [comment]
@whitingx at a quick glance I'm not sure if this particular suggestion would be suitable, however a solution like this would be worth considering but I think it best sit as it's own issue/suggestion.

As for lazy loading @maban, as you've tagged this 'help wanted' I recently used this https://github.com/kaizau/Lazy-Load-Images-without-jQuery which was quite lightweight and has no dependencies, which I could use on styleguides if that's easier.

**Comment by maban** [comment]
Done!
