### ISSUE TITLE
Twitter/Social Media Section?

### ISSUE THREAD

**Issue by whitingx** [maban/styleguides#175]
There seem to be a few Style Guide related Twitter accounts around e.g.

https://twitter.com/guardianstyle
https://twitter.com/styleguide
https://twitter.com/tnwstyle

Would be useful to have a section on the site to capture these and any other Style Guide related social media accounts (e.g. https://www.pinterest.com/explore/style-guides/)

**Comment by bradfrost** [comment]
Very interesting. I'm hesitant to add another section to the site (especially given our current small screen navigation pattern), but yeah this would probably be a good idea to track somewhere. I'm open to ideas.

**Comment by whitingx** [comment]
@bradfrost - as an idea, could merge the `podcasts` & the `style guide podcast` menu items to a generic `podcasts` menu item, this might also make it easier for contributors to know where to add any new podcast resources.

This would then free up a menu item space to include a `social media` area (might want a more descriptive name for this)

cc/ @maban

**Comment by maban** [comment]
@whitingx: the podcast suggestion is a very good one – I got confused by this the other day even though I built the damn thing.

I'll have a think about the social media suggestion. I like it, but I don't want people to think it's a link to _our_ social media accounts (if that makes sense).

**Comment by maban** [comment]
I've done your podcast suggestion – feels a lot better! Still not sure about making a section dedicated to social media though, as I don't think there's enough content to justify it. Perhaps I can create a twitter list on the styleguides.io twitter account, or we can add stuff to the "examples" section for now.
