### ISSUE TITLE
Remove Heroku’s “Purple” from Examples page

### ISSUE THREAD

**Issue by swashcap** [maban/styleguides#208]
Unfortunately, Heroku appears to have locked down their style guide for internal use only. https://purple.herokuapp.com/ authorizes with a Google account and yields the following response for me:

``` json
{"statusCode":401,"error":"Unauthorized","message":"Our apologies, but this page is restricted to heroku.com members only."}
```

😐

**Comment by bradfrost** [comment]
@swashcap yep, I've noticed that as well. I think I'm going to leave it on the site just in case that happens to change! Thanks
