### ISSUE TITLE
http://styleguides.maban.co.uk/ is returning a 404

### ISSUE THREAD

**Issue by crismanNoble** [maban/styleguides#24]
I was linked to http://styleguides.maban.co.uk/ from today's Sidebar email newsletter. It gave me a 404. I did some digging and found this repository and thought you might like to know.

**Comment by bjankord** [comment]
Ah I'm curious if this is related to the [CNAME update](https://github.com/maban/styleguides/commit/cdf611bbedb264e0ce29fc6013033f050bfc3f92)? Probably need to point traffic going to [styleguides.maban.co.uk](http://styleguides.maban.co.uk) towards [http://www.styleguides.io/](http://www.styleguides.io/)

Might want to point http://www.styleguides.io/ to non www too?

**Comment by quattromani** [comment]
also worth noting, syleguides.io working great in FF/safari, no worky in Chrome (DNS lookup failed)

**Comment by maban** [comment]
It's already set correctly, just got to wait a while for the DNS to do its thing.

**Comment by susanjrobertson** [comment]
It seems Chrome works, but only with the www in the front :)

**Comment by maban** [comment]
@bradfrost is looking into this – might take another day to straighten itself out.

**Comment by bradfrost** [comment]
Good news! I believe the issue is finally sorted out. We've checked on a bunch of browsers and environments and it appears to be working properly now. If you're still seeing issues, make sure you clear your browser cache.
