### ISSUE TITLE
Add list of contributors to footer

### ISSUE THREAD

**Issue by bjankord** [maban/styleguides#32]
I really like how the [a11yproject.com](http://a11yproject.com/) displays a list of contributors on their site, makes it feel more like a community-driven effort. 

What are your thoughts on adding something like that to this project? There is a jQuery plugin I can add to display contributors in the footer. I'm unsure about adding jQuery to the project for this plugin though. The plugin requires jQuery's getJSON method to call github's API.

**Comment by susanjrobertson** [comment]
I don't mind the idea of it, but agree that adding jQuery just for this seems a bit much. What say you @maban, @bradfrost, and other?

**Comment by maban** [comment]
I like the idea but this seems a bit much for now. I could add a static link in the footer to the contributors page on GitHub, but I don't really want to add JavaScript if it's not core to the content.

**Comment by susanjrobertson** [comment]
I think the link is a good compromise.

**Comment by bradfrost** [comment]
Eventually we'll have some additional functionality (such as tagging #27), but if yinz are hardcore to do all that vanilla then be my guest! I will sit back and wallow in a pool of my lacking JS skillz.

**Comment by maban** [comment]
I've added a link to the footer, it'll do for now.

**Comment by bjankord** [comment]
Cool, the link seems like a good solution to me. I was thinking jQuery was too heavy for this but didnt want to write a vanilla JS version of the getJSON method to interface with the github API.

**Comment by brendanfalkowski** [comment]
Will https://github.com/filamentgroup/shoestring instead of jQuery for a smaller size? I'm lacking on raw JS power also.
