### ISSUE TITLE
Standardizing image specs

### ISSUE THREAD

**Issue by brendanfalkowski** [maban/styleguides#36]
Was peeking at the images being uploaded and spotted a few +75 KB images. Think we need some standards sooner rather than later because 50 images x 50 KB = 2.5 MB page. Kind of blows jQuery out of the water if these aren't being optimized well.

I'm thinking 600x400 can cover up to 1920px wide screens at 1:1 pixel ratio, while doubling up for smaller hi-res screens. Most of the screenshots can be 8-bit PNGs so they'll take optimization very well.

Also, we could modify the grid to 4-per-row on giant screens, and use 400x300 (Dribbble-style) for less bandwidth yet. Any thoughts?

**Comment by brendanfalkowski** [comment]
Oh, just saw this: https://github.com/maban/styleguides/blob/gh-pages/_resourceexample/README.md

Guessing GH Pages can't do image resizing. Might be better to err on the smaller side?

**Comment by maban** [comment]
I was just thinking about this. I've been adding a bunch of images to the talks, and I wanted these to be a bit taller because they're replacing the heading. But with so many resources and images, that'll be a lot to download.

600x400 is going to be better than 800px wide. I'll have another think.

Also agree with the 4-per-row on giant screens.

**Comment by brendanfalkowski** [comment]
Was thinking 600x450 for talks (so 4:3) but then realized most of mine are widescreen (16:9) actually. Might be better to just set the width at 600 and let the talk determine its height.

I'll whack in the 4-per-row now.

**Comment by maban** [comment]
Great, thanks!

I went for 4:3 but noticed the same thing you did about them being widescreen. Good idea to just let the width determine the height, I just liked the consistency.

I'm wondering if the picture element might be appropriate here.

**Comment by bradfrost** [comment]
Is it possible to do a bit of lazy loading for the images? Being that this is a static site, a picture element approach might be hard to maintain.

**Comment by maban** [comment]
Yes, I think that'd be a good solution. I'm also wondering whether to only show images for recommended resources (to keep the load down).

I want to make it as easy as possible for people to add content so I take your point about picture element being hard to maintain. There might be an automated Jekyll/Grunt way of resizing images though, so I'll investigate that too.

I'm going to work more on some of these bigger things on Friday – that's my non-client-work day.

**Comment by brendanfalkowski** [comment]
Added 4-per-row for screens 1500px and wider: f8278e5e58a8b1121dab4ee72e0aa4ddebdff9d4

Rewrote the n-child use a bit, and thankfully worked first try :)

Edit: actually, needed a little fix: b2f55d00c4b0eb76dbef0d08dbaeb558a50d231c

**Comment by bradfrost** [comment]
>  I'm also wondering whether to only show images for recommended resources (to keep the load down). 

I think for non-example resources keeping it to the recommended resources is a good idea. I do think the examples section really benefits from having the thumbs there.

**Comment by maban** [comment]
How about…? on the home page, images only display on recommended resources. On the inner pages (like if you're on the example page or talk page) they all display.

**Comment by bradfrost** [comment]
That sounds great to me!
