### ISSUE TITLE
Open Links in new windows

### ISSUE THREAD

**Issue by sirjamesgray** [maban/styleguides#380]
I'd love to see if others are interested in "open in new tab" being the default behavior of clicking the external links on the home page.

This will allow people to jump into the linked documentation of each design system without having to scroll through the tons of pages in their history to find the styleguides site again.

Sure, chrome could help us out by automatically grouping history by url, but that's probably not gonna happen soon.

**Comment by maban** [comment]
Thanks for the feedback, @sirjamesgray! I'd like to avoid doing this as opening links in a new tab on the user's behalf is not a recommended practice as it messes with the default behaviour of the browser, and makes links work on the site inconsistently. If users wish to open links in new tabs, they can choose to do this (such as using command+click on a Mac).
