### ISSUE TITLE
Git checkout fails because of a too long filename

### ISSUE THREAD

**Issue by d2s** [maban/styleguides#417]
Tried to clone the repository, but couldn't checkout the tree (when using a Linux desktop).
Problem is caused by the painfully long filename for the Apple Watch Human Interface Guidelines.

- [/images/screenshots/ https_developer.apple.com_library_prerelease_ios_documentation_UserExperience_Conceptual_WatchHumanInterfaceGuidelines_index.html_apple_ref_doc_uid_TP40014992-CH3-SW1.jpg](https://github.com/maban/styleguides/blob/gh-pages/images/screenshots/https_developer.apple.com_library_prerelease_ios_documentation_UserExperience_Conceptual_WatchHumanInterfaceGuidelines_index.html_apple_ref_doc_uid_TP40014992-CH3-SW1.jpg)

### Terminal output

```
$ git clone https://github.com/maban/styleguides.git 

Cloning into 'styleguides'...
remote: Counting objects: 6657, done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 6657 (delta 36), reused 34 (delta 17), pack-reused 6585
Receiving objects: 100% (6657/6657), 32.24 MiB | 10.11 MiB/s, done.
Resolving deltas: 100% (3536/3536), done.
error: unable to create file images/screenshots/https_developer.apple.com_library_prerelease_ios_documentation_UserExperience_Conceptual_WatchHumanInterfaceGuidelines_index.html_apple_ref_doc_uid_TP40014992-CH3-SW1.jpg: File name too long
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

### Software versions

```sh
$ git --version
git version 2.11.0
```

### Solution

- [ ] Use another operating system to rename the file.
- [ ] Commit the changed file to the repository.
- [ ] Allow others to checkout the repository so they could contribute.

**Comment by Spone** [comment]
Here you go: #420
