### ISSUE TITLE
Styleguide or style guide?

### ISSUE THREAD

**Issue by brendanfalkowski** [maban/styleguides#44]
Personally, I'm right on the fence between styleguide or style guide? Wonder if we might discuss that.

I like concatenated phrases because it becomes a thing, but I'd never write brandguide so I kind of lean the other way.

**Comment by michaelthorne** [comment]
> Style Guide

:100:

When it comes to URLs, concatenation makes sense: `styleguide` | `styleguides`, etc.

**Comment by bradfrost** [comment]
+1 for Style Guides. Although I'm not too miffed either way.

**Comment by maban** [comment]
Style Guide. That's what my editor said anyway. He also tells me off for writing "icecream" instead of "ice cream". I'm always getting it wrong regardless.

**Comment by brendanfalkowski** [comment]
Style guide it is.

@michaelthorne I'd agree for domain names (styleguide) but I always like to see paths dashed out (x.com/style-guide).

**Comment by bjankord** [comment]
Style Guide is what I use, in urls I write is as style-guide.
