### ISSUE TITLE
Wufoo Form for submitting

### ISSUE THREAD

**Issue by bradfrost** [maban/styleguides#47]
So I ran into this a lot on [This Is Responsive](http://bradfrost.github.io/this-is-responsive/index.html). A lot of people want to help, but find tools like Github confusing and intimidating (and I can't say I blame them). 

I'd like to set up a Wufoo form so that people can submit resources without having to go through Github. I'm happy to monitor the submissions (in my experience it's certainly not a firehouse) and add them to the pile. It's just a nice way to be more inclusive for non-technical folks who want to help the cause.

**Comment by brendanfalkowski** [comment]
Sounds like a good idea. I'd only done like two pull requests before this (not much hand-holding from GitHub yet) so it'd be nice for people who aren't going to learn that just to share a link.

**Comment by bradfrost** [comment]
Alright, the form is live: https://bradfrost.wufoo.com/forms/add-resource-to-styleguidesio/

Where are we thinking we can put this? We have that nice "Add an example" tile at the end of each grid, which would be nice to include a link to the form there. But for now it might make sense to link it up in the `README.md` files like [we have here](https://github.com/maban/styleguides/tree/gh-pages/_resourceexample). Although to be honest, that looks pretty damn intimidating if I wasn't used to it. I dunno. Open to suggestions.

**Comment by brendanfalkowski** [comment]
We could make a "contributing" page and link to that from each section instead. Describe the two options briefly with links out. People that know GH won't have too much trouble using the READMEs.

**Comment by maban** [comment]
This is something my colleague @elrat was suggesting to me yesterday – she's not used Jekyll before so I asked her to run through the steps to add a resource, to make sure the README was explanatory enough. She said she found it jarring to get sent to a GitHub page, and that would put her off contributing, even if the explanation was good.

I think a "contributing" page would really help. So when the user clicks "add a link", it would take them to a page/screen that gives them 2 options: add via Github or Wufoo (with the Wufoo form inline).

I can set this up on Friday.

@elrat also suggested an "about" page, and I think this would be a great place to add the contributors section that was talked about – that way we can just include JS for that page.

**Comment by susanjrobertson** [comment]
Just catching up here, all of this is super great. I :heart: Github, but so many people don't that I love the form. Well done @bradfrost! @maban if you need help setting something else up, let me know, I have time :smile_cat:

**Comment by maban** [comment]
Assigning this to me. Going to get Brad's form on the site tomorrow.

**Comment by maban** [comment]
I've added something in: https://github.com/maban/styleguides/commit/e93788441736a3de908adedccf6e6b4173c013b8 – let's see how it goes :)

**Comment by michaelthorne** [comment]
@maban Thanks, that's cool.

I made a small update to how it works on the home page: https://github.com/maban/styleguides/pull/67 I didn't merge it in yet, wanted to get your opinion first.

**Comment by maban** [comment]
Thanks so much for spotting this, and pushing a fix! You're a star :)

**Comment by michaelthorne** [comment]
No worries! Happy for me to merge my pull request?

**Comment by maban** [comment]
Done! (I forgot to press the second big green button)

**Comment by michaelthorne** [comment]
Cool :smile:
