### ISSUE TITLE
Renaming "Recommended"?

### ISSUE THREAD

**Issue by martinwolf** [maban/styleguides#75]
Hej,

styleguides.io is a great ressource and I like what you're doing.
What attracted my attention right away was the Recommended tag. In my opinion the wording is a little bit unfortunate, because I guess all links are recommended otherwise they wouldn't be on the site, right?

How about renaming it to "Favourite", "Staff Favourite", "Special", "Extra", "Noteworthy" or something along those lines?

Anyway, thanks for your time and effort. Just a suggestion. :)

Cheers,
Martin

**Comment by maban** [comment]
That's a good point, Martin, and I like your suggestions.

I personally like "noteworthy" the most, and I also like "favourite". @bradfrost, @susanjrobertson, @brendanfalkowski, @Ianfeather, @michaelthorne – what do you think?

**Comment by michaelthorne** [comment]
@martinwolf Agreed. @maban I think "Favourite" is good too. Another possibility is "Featured", although that could imply for a limited period only...

**Comment by bradfrost** [comment]
Or maybe just a simple star?

On Thursday, December 11, 2014, Michael Thorne notifications@github.com
wrote:

> @martinwolf https://github.com/martinwolf Agreed. @maban
> https://github.com/maban I think "Favourite" is good too. Another
> possibility is "Featured", although that could imply for a limited period
> only...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maban/styleguides/issues/75#issuecomment-66607119.

## 

---

Brad Frost
http://bradfrost.com
http://twitter.com/brad_frost

**Comment by bjankord** [comment]
I like the star idea.

**Comment by susanjrobertson** [comment]
I like the star idea or I think favorite would work as well (whichever spelling ;) )

**Comment by maban** [comment]
Yay! a star is cool! I'll make that change either tonight or tomorrow.

**Comment by michaelthorne** [comment]
:star: :+1:

**Comment by maban** [comment]
I realised it's just one line of code. Done!

**Comment by brendanfalkowski** [comment]
Kapow!

**Comment by martinwolf** [comment]
Yeah! :dancer:
