### ISSUE TITLE
_layouts page.html needs a lang attribute

### ISSUE THREAD

**Issue by fstorr** [maban/styleguides#77]
Hi

A quick accessibility fix for you good people:

_layouts page.html needs a `lang` attribute to meet the [WCAG 2.0 "Language Of A Page" requirement](http://www.w3.org/TR/2008/REC-WCAG20-20081211/#meaning-doc-lang-id).

Keep up the good work :)

**Comment by bjankord** [comment]
This has been fixed with #78
