### ISSUE TITLE
Separate Frameworks from Tools section

### ISSUE THREAD

**Issue by robhrt7** [maban/styleguides#85]
Hi,

It's very confusing to mess up Frameworks, Starting templates and Tools in one section. Currently first five projects in this section are not Tools - Barebones, Bootstrap, Foundation etc. Also Style Tyles that is an approach, not a tool, must be listed in the direffent section.

Let discuss additional section names for those items, that doesn't fit for Tools group.

**Comment by bradfrost** [comment]
Hey @operatino,
Thanks for the suggestion. I don't think it's going to be possible to make a new page for each of these areas, but perhaps we can add a tagging system similar to the [examples](http://styleguides.io/examples.html) page. Thanks again for the suggestion!

**Comment by robhrt7** [comment]
Yeah, of course we don't need a ton of sections, would be enough having tags and split Tools section to two different one. It's really hard to find real tools among frameworks.

**Comment by brendanfalkowski** [comment]
I may have a way to help with this. Incoming...
