### ISSUE TITLE
More styleguides resources

### ISSUE THREAD

**Issue by montogeek** [maban/styleguides#87]
Hi!
I just discovered this repo 3 minutes ago on Twitter, I have been doing the same, compiling resources/tools/examples for creating CSS Guidelines on https://github.com/montogeek/guidelines.

I think some of the links can be added to this resources repo. If so, can I add all the links that are missing here?

Thank you!

**Comment by bradfrost** [comment]
Hey @montogeek! Thanks for sharing your resource compilation. That was the genesis of this project, too. We all had our own little collections going, so we decided to make an uber resource! It looks like all of the links provided are covered on the site (minus I think one that's just a collection of style guides included elsewhere), but definitely feel free to add more resources as you come across them!

Thanks again,
B
