### ISSUE TITLE
Talk titles and info missing

### ISSUE THREAD

**Issue by susanjrobertson** [maban/styleguides#96]
I noticed when I added my SmashingConf talk to the talk list that a lot of them aren't showing the titles or the footer by and conf info. I didn't have time to look into it today, but am leaving this here for a reminder to take a closer look.

**Comment by maban** [comment]
Oh! That sounds like a Jekyll template thing! Probably something that used to work and then I broke it when I made some changes to the site. I'm doing some stuff on the site tomorrow morning so I'll have a look at it then.

**Comment by maban** [comment]
Is this working now? Did I or someone else fix it?

**Comment by susanjrobertson** [comment]
I'm still seeing the issue on the site right now. For example, Jina Bolton's talk from CSSConfEU doesn't have a title, neither does Natalie Down's from Girl Geeks of Brighton, so not sure what is up. I can take a look at it later this week if you want.

**Comment by maban** [comment]
That was me – I set it so that a title wouldn't be displayed if there was an image, the reasoning being that the talk image contains the title so it would be duplicated. But I think that's confusing, so I've set it back.
